
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/Applications/CMake.app/Contents/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:38 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 22.6.0 - x86_64
...
